export function generateProjectFiles(blueprint = {}) {
  const appName = safeString(blueprint.name, "AI Generated App");
  const theme = blueprint.theme === "dark" ? "dark" : "light";
  const primaryColor = safeString(blueprint.primaryColor, "#ff5a1f");
  const heroText = safeString(blueprint.heroText, "Welcome to your generated app.");
  const buttonLabel = safeString(blueprint.buttonLabel, "Get Started");
  const layout = blueprint.layout === "grid" ? "grid" : "stack";
  const screens = normalizeScreens(blueprint.screens);

  return {
    "package.json": json({
      name: toKebabCase(appName) || "ai-generated-app",
      private: true,
      version: "1.0.0",
      type: "module",
      scripts: {
        dev: "vite",
        build: "vite build",
        preview: "vite preview"
      },
      dependencies: {
        react: "^18.2.0",
        "react-dom": "^18.2.0"
      },
      devDependencies: {
        vite: "^6.1.0"
      }
    }),
    "README.md": makeReadme(appName),
    "index.html": makeIndexHtml(appName),
    "src/main.jsx": makeMainFile(),
    "src/styles.css": makeStyles(theme, primaryColor, layout),
    "src/components/PrimaryButton.jsx": makeButtonComponent(),
    "src/pages/HomePage.jsx": makeHomeComponent(buttonLabel),
    "src/App.jsx": makeAppFile(appName, heroText, screens),
  };
}

function makeReadme(appName) {
  return [
    `# ${appName}`,
    "",
    "Generated by the AI App Builder MVP.",
    "",
    "## Run locally",
    "",
    "```bash",
    "npm install",
    "npm run dev",
    "```",
  ].join("\n");
}

function makeIndexHtml(appName) {
  return [
    "<!doctype html>",
    '<html lang="en">',
    "  <head>",
    '    <meta charset="UTF-8" />',
    '    <meta name="viewport" content="width=device-width, initial-scale=1.0" />',
    `    <title>${escapeHtml(appName)}</title>`,
    "  </head>",
    "  <body>",
    '    <div id="root"></div>',
    '    <script type="module" src="/src/main.jsx"></script>',
    "  </body>",
    "</html>",
  ].join("\n");
}

function makeMainFile() {
  return [
    'import React from "react";',
    'import ReactDOM from "react-dom/client";',
    'import App from "./App";',
    'import "./styles.css";',
    "",
    'ReactDOM.createRoot(document.getElementById("root")).render(',
    "  <React.StrictMode>",
    "    <App />",
    "  </React.StrictMode>",
    ");",
  ].join("\n");
}

function makeStyles(theme, primaryColor, layout) {
  const isDark = theme === "dark";
  return [
    ":root {",
    `  --primary: ${primaryColor};`,
    `  --bg: ${isDark ? "#0f172a" : "#f8fafc"};`,
    `  --text: ${isDark ? "#e2e8f0" : "#0f172a"};`,
    "}",
    "body { margin: 0; font-family: Inter, system-ui, sans-serif; background: var(--bg); color: var(--text); }",
    ".app-shell { max-width: 920px; margin: 24px auto; padding: 16px; }",
    `.feature-list { display: ${layout === "grid" ? "grid" : "block"}; gap: 12px; grid-template-columns: repeat(2, minmax(0, 1fr)); padding-left: 18px; }`,
    ".primary-btn { background: var(--primary); border: none; color: #fff; border-radius: 8px; padding: 10px 14px; font-weight: 700; cursor: pointer; }",
    ".preview-card { border: 1px solid rgba(148,163,184,0.35); border-radius: 10px; padding: 12px; background: rgba(255,255,255,0.04); }",
  ].join("\n");
}

function makeButtonComponent() {
  return [
    'export default function PrimaryButton({ label = "Get Started" }) {',
    '  return <button className="primary-btn">{label}</button>;',
    "}",
  ].join("\n");
}

function makeHomeComponent(buttonLabel) {
  return [
    'import PrimaryButton from "../components/PrimaryButton";',
    "",
    "export default function HomePage() {",
    "  return (",
    '    <div className="preview-card">',
    '      <h2 style={{ marginTop: 0 }}>Home</h2>',
    '      <p>This page was generated from your prompt.</p>',
    `      <PrimaryButton label=${JSON.stringify(buttonLabel)} />`,
    "    </div>",
    "  );",
    "}",
  ].join("\n");
}

function makeAppFile(appName, heroText, screens) {
  return [
    'import HomePage from "./pages/HomePage";',
    "",
    "export default function App() {",
    `  const screens = ${JSON.stringify(screens.map((screen) => screen.title), null, 2)};`,
    "  return (",
    '    <main className="app-shell">',
    `      <h1>${escapeJs(appName)}</h1>`,
    `      <p>${escapeJs(heroText)}</p>`,
    '      <ul className="feature-list">',
    "        {screens.map((screen) => (",
    "          <li key={screen}>{screen}</li>",
    "        ))}",
    "      </ul>",
    "      <HomePage />",
    "    </main>",
    "  );",
    "}",
  ].join("\n");
}

function normalizeScreens(screens) {
  if (!Array.isArray(screens) || screens.length === 0) return [{ title: "Home" }];
  return screens.map((screen, index) => ({ title: safeString(screen?.title, `Screen ${index + 1}`) }));
}

function safeString(value, fallback) {
  return typeof value === "string" && value.trim() ? value.trim() : fallback;
}

function toKebabCase(value) {
  return String(value || "")
    .replace(/([a-z])([A-Z])/g, "$1-$2")
    .replace(/[^a-zA-Z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .toLowerCase();
}

function escapeHtml(value) {
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;");
}

function escapeJs(value) {
  return String(value).replaceAll("`", "");
}

function json(value) {
  return JSON.stringify(value, null, 2);
}
